### ISSUE TITLE
No archive today? (2015-04-23)

### ISSUE THREAD

**Issue by jerodsanto** [igrigorik/githubarchive.org#100]
During today's Nightly run, we got this error:

```ruby
BigQuery::Errors::BigQueryError: FROM clause with table wildcards matches no table
```

I extracted the query itself and ran it in the BigQuery query runner. Same error. I then switched the date to `2015-04-22` and it works OK. Also, this 404s:

```
wget http://data.githubarchive.org/2015-04-23.json.gz
```

I'm guessing there was no archive generated today?

**Comment by igrigorik** [comment]
@jerodsanto one of those `<facepalm>` bugs.. looks like API changed one of the strings I was looking for, which caused the BQ imports to error out for the 23rd. Fixed code, populating BQ now...

Re, wget: the archives are there, but they're only available in hourly format, so you need 2015-04-23-{0...23}.json.gz

**Comment by jerodsanto** [comment]
@igrigorik thanks! I misunderstood the wget format. Makes sense.
