### ISSUE TITLE
Missing archive data for 2015

### ISSUE THREAD

**Issue by hut8** [igrigorik/githubarchive.org#101]
Thanks for githubarchive! I'm trying to make something with the data.

I noticed there were some issues with missing data before, like  #90 and #82. You fixed both of these; I don't think this is a duplicate. #82 said that files starting 2015-01-07-13 were missing. But right before that, it seems like 2015-01-05-22 → 2015-01-06-23 are all missing except a couple. Here's a list of errors:

```
error: http://data.githubarchive.org/2015-01-05-22.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-05-23.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-0.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-1.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-2.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-3.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-4.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-6.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-7.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-8.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-9.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-10.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-11.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-12.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-13.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-14.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-15.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-16.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-17.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-18.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-19.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-20.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-21.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-01-06-23.json.gz (404 Client Error: Not Found)
error: http://data.githubarchive.org/2015-03-18-19.json.gz (404 Client Error: Not Found)
```
Any hope of getting these somehow? What's up with the one in March? Are these just because of GitHub downtime? Your server's downtime? Or did  `-a public-read` or something get skipped when copying?

On a side note, would it benefit you to have a mirror of the archive? I'd imagine the outgoing bandwidth from Google adds up. Isn't it like $0.12/GB of network egress? So if one person downloads everything for a year that would be, very roughly (for this year through 2016-01-01) about 50GB. So that's six bucks to download the year one time! But I'm probably using the wrong figures because that seems excessive.

**Comment by igrigorik** [comment]
Thanks for the heads up. It looks like I forgot to backfill Jan 5/6 after fixing an issue in the new pipeline.. Looking at March 18, not sure what happened there -- looks like a network error. That said, uploaded the files so everything should be in place now. Let me know if you stumble over anything else.

Re, mirroring: if possible, yes please be careful with overly aggressive downloads.. but, other then that, no the cost part is not a big issue -- the Google Cloud team has kindly offered to sponsor the project :)

**Comment by hut8** [comment]
Thanks very much! This project is amazing.
