### ISSUE TITLE
Duplicate events?

### ISSUE THREAD

**Issue by hut8** [igrigorik/githubarchive.org#102]
Today, I was trying to build a unique index on the `event_id` field, but it looks like there are a lot of duplicates. I've downloaded the entire 2015 archive except the last few days, and there are 215 entries that are non-unique. Do you have any insight into that? I was more worried about the possibility of missing events somehow.

**Comment by igrigorik** [comment]
Do all the fields on those event_id's match as well? As in, are they "full duplicates"? Also, do they come in groups, or are they spread out? 

FWIW, the crawler logic should be fairly robust at this point. You can double it check it here: https://github.com/igrigorik/githubarchive.org/blob/master/crawler/crawler.rb

**Comment by hut8** [comment]
Yes, they’re definitely full duplicates. Same fields and everything. They actually do seem to come in groups, which I hadn’t noticed until you asked. There are a large number of duplicates, for example, in 2504069xxx. Thanks for the quick reply.

**Comment by igrigorik** [comment]
Ah, then I think I have a theory. The crawler is stable, but on a rare occasion where it needs to be rebooted it loses its "seen history" and hence logs a set of duplicates on first post-reboot fetch. This is fixable: start crawler, read the archive and load last N entries, etc.. just haven't got around to it.

**Comment by hut8** [comment]
Yeah that seems very likely. In the mean time would you like the JSON files with de-duplicated data?

**Comment by igrigorik** [comment]
If you have those handy, sure!

**Comment by hut8** [comment]
[This is "showing my work"](http://githubcontributions.io/deduped-archives/)
[The .json.gz files](http://githubcontributions.io/deduped-archives/output)

Please double-check everything before actually uploading those, if you choose to do so at all. Thanks!

**Comment by igrigorik** [comment]
Hmm, that's more files than I anticipated.. Perhaps there is something else going on here then. The crawler is not restarted that often -- I'll take a closer look at the logs this weekend.

**Comment by hut8** [comment]
A couple of them, including 01-07-0 and 05-05-15, had relatively large numbers of duplicates that seemed to indicate what you described. A couple, like 04-15-0 had one duplicate which is pretty mysterious.

**Comment by igrigorik** [comment]
Didn't find anything suspicious in my logs, it could well be that GitHub's API is acting up every once in a while. Closing this as a wontfix.
