### ISSUE TITLE
Setup and installation.

### ISSUE THREAD

**Issue by datomnurdin** [igrigorik/githubarchive.org#103]
Is there any setup or installation documentation for this library? I plan to use this library to crawl the github data an store in my own BigQuery for my research. Thanks.

**Comment by igrigorik** [comment]
@datomnurdin if you want a private copy you might be better off just doing a `bq cp` on existing tables -- that'll save you a lot of time and give you access to past data. 

That said, if you do want to run your own copy of the crawler, all the code is at: https://github.com/igrigorik/githubarchive.org/tree/master/crawler - search for "ruby Procfile" for a guide on how to get started.

**Comment by datomnurdin** [comment]
TQVM sir .

**Comment by datomnurdin** [comment]
BTW, is it possible if I copy the existing table and continue crawl the github data?

**Comment by igrigorik** [comment]
You can setup a periodic job to copy the latest tables. Alternatively, yes you can run your own crawler... but copying might be a lot easier :)
