### ISSUE TITLE
Missing data for 0000 to 1000 hours everyday

### ISSUE THREAD

**Issue by knightsamar** [igrigorik/githubarchive.org#105]
I am downloading data from right from Dec 1st 2014 00 hours and I have found that data for all hours from *00 hours to 09 hours* everyday is **missing**. I have seen this occur for all days until March 1st 2015. Yet to work with days after that.

Is it some problem in the way I am requesting files or is the data really not present ?

Some sample file names that I found to be missing:

* 2014-12-01-09.json.gz
* 2014-12-02-01.json.gz
* 2014-12-08-09.json.gz
* 2014-12-17-08.json.gz
* 2014-12-07-06.json.gz
* 2014-12-27-09.json.gz
* 2015-01-01-08.json.gz
* 2015-01-02-09.json.gz

**Comment by igrigorik** [comment]
The issue is the 0 prefix.. 

- http://data.githubarchive.org/2014-12-01-9.json.gz
- http://data.githubarchive.org/2014-12-02-1.json.gz
- ... 

That should do the trick :)
