### ISSUE TITLE
Enable CORS on data.githubarchive.org?

### ISSUE THREAD

**Issue by anvaka** [igrigorik/githubarchive.org#106]
Hi Ilya,

Would it be possible to enable CORS on data.githubarchive.org? I'd love to use it for in-browser visualization of GitHub activity, and wanted to avoid extra step of downloading it to my servers before serving to clients.

Thank you!

**Comment by igrigorik** [comment]
@anvaka definitely possible, but on the client.. you'll be getting a gzip'ed asset, and these are fairly large downloads even when compressed (10MB+ per 1hr archive). Are these viable requirements?

**Comment by anvaka** [comment]
Yes, I understand. I think the runtime should still be able to handle this pretty well.

**Comment by igrigorik** [comment]
```
$> gsutil cors get gs://data.githubarchive.org/
[{"origin": ["https://data.githubarchive.org"], "responseHeader": ["Content-Type"], "method": ["GET", "HEAD"], "maxAgeSeconds": 86400}]
```

I believe that should do the trick.

**Comment by anvaka** [comment]
Uhm, I still don't see `Access-Control-Allow-Origin` present in the response. Also [this simple test](http://client.cors-api.appspot.com/client#?client_method=HEAD&client_credentials=false&server_url=http%3A%2F%2Fdata.githubarchive.org%2F2015-01-01-15.json.gz&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote) shows error in the network panel. I also verified over https, with no luck.

I was reading [gsutil cors docs](https://cloud.google.com/storage/docs/gsutil/commands/cors), looks like to enable it for a bucket you need to save a json config file (e.g. `~/cors-config.json`:

``` json
[{
    "origin": ["*"],
    "responseHeader": ["Content-Type"],
    "method": ["GET", "HEAD"],
    "maxAgeSeconds": 86400
}]
```

And then `gsutil cors set ~/cors-config.json gs://data.githubarchive.org/`

**Comment by igrigorik** [comment]
Doh, you're right.. I need `*` on the origin policy. Fixed.

**Comment by anvaka** [comment]
Thank you so much, Ilya! Works like a charm.
