### ISSUE TITLE
[question] Is it possible to get a number of Clones?

### ISSUE THREAD

**Issue by kkamkou** [igrigorik/githubarchive.org#109]
Like the `Traffic` tab in the `Graphs` section?
It would be very-very useful. Thank you.

**Comment by igrigorik** [comment]
Not directly. But you should be able to approximate it by counting number of fork events: https://developer.github.com/v3/activity/events/types/#forkevent

**Comment by kkamkou** [comment]
That I know. But fork is not a clone. Ok, thanks
