### ISSUE TITLE
FROM clause with table wildcards matches no table

### ISSUE THREAD

**Issue by datomnurdin** [igrigorik/githubarchive.org#117]
I got this error message when running this query

```
SELECT type,  COUNT(*) FROM (
  TABLE_DATE_RANGE([day.events], 
    TIMESTAMP('2013-1-01'), 
    TIMESTAMP('2015-08-28')
  ))
WHERE actor.login = "datomnurdin"
GROUP BY type;
```
P.S:  I'm using private copy.

Please advice.

**Comment by igrigorik** [comment]
You need a trailing "_" on events -- `day.events_`. Also, note that new event tables start from 2015-01-01. Data prior to that is in the other tables (for now).
