### ISSUE TITLE
Repository stargazers column

### ISSUE THREAD

**Issue by cirosantilli** [igrigorik/githubarchive.org#118]
EDIT: I've just learned now that timeline is deprecated, and that I had been looking at the new Events API instead... If someone can point me to the docs for the timeline API, I might find out the answer by myself.

Is there a reason why there is no `repository_stargazers_count`  column?

For example, there is `repository_watchers`, I suppose it comes from https://developer.github.com/v3/activity/events/types/#createevent `repository -> watchers`. Can't we also use the sibling `stargazers_count`? That would be a great metric.

BTW I've just noticed, what is the difference between `watchers` and `watchers_count` ?

**Comment by igrigorik** [comment]
The data in the archive mirrors what GitHub provided, we don't do any of our own aggregations.

For latest format of the events, see:
https://developer.github.com/v3/activity/events/
