### ISSUE TITLE
How is it possible that there are "repository_private = true" events?

### ISSUE THREAD

**Issue by cirosantilli** [igrigorik/githubarchive.org#119]
Query:

    SELECT * FROM [githubarchive:github.timeline] WHERE repository_private = 'true'

Only 1k of them.

**Comment by hsborges** [comment]
The table timeline was deprecated. Click on 'details' to see the message.

**Comment by cirosantilli** [comment]
@hsborges thanks for teaching me that!

**Comment by cirosantilli** [comment]
@hsborges do you know where the old timeline API is documented?

**Comment by hsborges** [comment]
No, I'm sorry.

**Comment by igrigorik** [comment]
@cirosantilli see https://www.githubarchive.org/#bigquery for some details on the schema. 

Re, private: my guess is, you're see activity from repos that were private but then were made public.
