### ISSUE TITLE
How to setup my own crawler and copy automatically into BigQuery?

### ISSUE THREAD

**Issue by datomnurdin** [igrigorik/githubarchive.org#121]
Actually I already doing some research about how to crawl and copy automatically into BigQuery since 21/5/2015 but I still got no idea how to setup this thing. From my understanding I need to setup the crawler first and then upload it into big query if not mistaken. Any detail instruction how to setup this?

Please advice. Thank you.

**Comment by igrigorik** [comment]
For context, why do you need to create a copy of the dataset? The `githubarchive` project is open for anyone to query and automatically kept up to date.

**Comment by datomnurdin** [comment]
What happen if one day githubarchive project will take down from Google Big Query?

**Comment by igrigorik** [comment]
Ah, I see. A backup plan is always good to have I guess. That said, and for the record, the BigQuery team has kindly sponsored this project and I don't believe there are any plans to change that.

That said, if you want to mirror the data then your best bet is to mirror the underlying gzip archives, which you can download from data.githubarchive.org. You don't need to run your own crawler.. just download and mirror the archives somewhere else if you want a backup.
