### ISSUE TITLE
Year.2015 Data

### ISSUE THREAD

**Issue by matthew-z** [igrigorik/githubarchive.org#129]
Hi

I noticed that the data archive of 2015 has not been released, I think you might have existing code to convert month-format data into a collection of year-format data. Could you tell me that if you would like to do the transformation later?

**Comment by igrigorik** [comment]
Starting beginning of 2015 we converted to new daily events format.. To scan the entire year, just change the start-end timestamps in this TABLE_DATE_RANGE query: https://www.githubarchive.org/#bigquery

**Comment by matthew-z** [comment]
I see, thank you
