### ISSUE TITLE
Bad gzip in one of the archives.

### ISSUE THREAD

**Issue by mikeal** [igrigorik/githubarchive.org#136]
Getting an error parsing one of the archive files using Node.js zlib.

```
Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:363:17)
```

It's this file [http://data.githubarchive.org/2016-01-28-1.json.gz](http://data.githubarchive.org/2016-01-28-1.json.gz), not sure why this one is messed up but I get this error consistently.

**Comment by mikeal** [comment]
Here's a quick script to reproduce.

```javascript
var request = require('request')
var zlib = require('zlib')

request('http://data.githubarchive.org/2016-01-28-1.json.gz').pipe(zlib.createGunzip())
```

**Comment by igrigorik** [comment]
Can you narrow it down to a line number and extract the offender?

**Comment by mikeal** [comment]
Actually, it's simpler than that, it's not a bad gzip, it's literally missing.

```
curl http://data.githubarchive.org/2016-01-28-1.json.gz   
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>
```

**Comment by igrigorik** [comment]
Ah. I think that's due to their API going down: https://status.github.com/messages/2016-01-31 - no API, no data.

**Comment by mikeal** [comment]
Oh, ok, was all of GitHub down?

**Comment by igrigorik** [comment]
Yeah, the whole site went down: https://github.com/blog/2106-january-28th-incident-report
