### ISSUE TITLE
What's the license of GitHub Archive Data?

### ISSUE THREAD

**Issue by anvaka** [igrigorik/githubarchive.org#137]
Couldn't find this anywhere...

**Comment by igrigorik** [comment]
Official answer from GitHub:

> The API is free to use, but you need to follow our [Terms of Service](https://help.github.com/articles/github-terms-of-service/). Especially keep in mind our prohibition against spam, which often comes into play with regards to API use:
> 
>> You must not upload, post, host, or transmit unsolicited email, SMSs, or "spam" messages.
> 
> In addition, if you are pulling content from repositories, it may be subject to the terms of the repo's project.
> 
> If you are pulling and republishing personal information about individuals, please be take a look at our [privacy policy](https://help.github.com/articles/github-privacy-policy/). Using the API in a way that violates individuals' privacy, such as pulling information from a repository that publishes private personal information of third parties without consent is not permitted.

**Comment by igrigorik** [comment]
Closing, feel free to reopen if that doesn't answer your question.
