### ISSUE TITLE
Running bigquery requests with an API client

### ISSUE THREAD

**Issue by mikeal** [igrigorik/githubarchive.org#138]
I'm not sure if this is the best place to ask this but it's basically the only place :)

I'm using the node.js client for the google APIs. I can access various metadata about the githubarchive data but it won't let me run any queries. Simple queries that I can run fine in the https://bigquery.cloud.google.com web interface return permission errors like this one when using the client:

```
Access Denied: Job githubarchive:job_GF9pOXgdaXWXcxYHNN6z97fTdZ4: The user github-analysis@github-analysis-1286.iam.gserviceaccount.com does not have permission to run a query in project githubarchive
```

Any idea what I need to do in order to be able to run some queries?

**Comment by igrigorik** [comment]
/cc @fhoffa 

My understanding is: you need to create own project, with BigQuery ACL's, and configure your client to use that. With that in place, you can query the public dataset.

**Comment by mikeal** [comment]
I did all that, I needed to do that just in order to get the metadata on the public dataset, but I'm still getting that permission error when attempting a query :(

**Comment by mikeal** [comment]
Also, the timeline dataset seems to not be up to date. Any reason why?

**Comment by mikeal** [comment]
It appears that the timeline data stops at some time in January of 2015.

```
SELECT type
FROM [githubarchive:github.timeline] 
WHERE (REGEXP_MATCH(created_at,'^2015-02'))
LIMIT 5
```

Returns no results.

**Comment by igrigorik** [comment]
We switched to "day" dataset in Jan 1, 2015: https://www.githubarchive.org/#bigquery

**Comment by mikeal** [comment]
ya, there's just a lot less info in this schema, a lot of the repo info (like language) is now gone.

**Comment by LaplaceG** [comment]
Also been looking for language information post 2014. Seems to discontinued at the same time as the switch to JSON format for payload?

**Comment by igrigorik** [comment]
@LaplaceG @mikeal correct, the new GH API does not report language -- not sure why. To my knowledge, that's the only major missing piece.

**Comment by igrigorik** [comment]
@mikeal did you get this working? Can we close this?

**Comment by igrigorik** [comment]
Closing, feel free to reopen if needed.

**Comment by ApopheniaPays** [comment]
> I did all that, I needed to do that just in order to get the metadata on the public dataset, but I'm still getting that permission error when attempting a query :(

Same problem, 4 years later, and the thread seems to have abandoned the issue shortly after opening it. Was this ever resolved?
