### ISSUE TITLE
BigQuery daily table isn't being created

### ISSUE THREAD

**Issue by zthomas** [igrigorik/githubarchive.org#139]
I have an app that allows people to search and get latest trends from github, [www.gitlogs.com](http://www.gitlogs.com), It uses data from the latest daily bigquery table but it looks like no tables were created for today, [events_20160520] 

Did something change?

Thanks for the awesome work on Githubarchive

**Comment by igrigorik** [comment]
Doh, looks like GitHub fiddled with their actor schema, which is why the BQ imports are bailing out.

Fixed the processing on this end, running the catchup imports now.. Should be done in an ~hour or two.
