### ISSUE TITLE
missing hourly dumps

### ISSUE THREAD

**Issue by slang800** [igrigorik/githubarchive.org#141]
year | total dumps | total missing
---- | ----------- | --------------------
2011 | 720         | 0 (after 2011-12-01)
2012 | 8765        | 19
2013 | 8751        | 9
2014 | 8747        | 13
2015 | 8760        | 0
2016 | 3558        | 1 (up to 2016-05-28)

URLs that return 404:

- http://data.githubarchive.org/2012-03-01-8.json.gz
- http://data.githubarchive.org/2012-03-05-4.json.gz
- http://data.githubarchive.org/2012-03-05-5.json.gz
- http://data.githubarchive.org/2012-03-05-6.json.gz
- http://data.githubarchive.org/2012-03-05-7.json.gz
- http://data.githubarchive.org/2012-03-10-10.json.gz
- http://data.githubarchive.org/2012-03-10-11.json.gz
- http://data.githubarchive.org/2012-03-10-12.json.gz
- http://data.githubarchive.org/2012-03-10-13.json.gz
- http://data.githubarchive.org/2012-03-10-14.json.gz
- http://data.githubarchive.org/2012-03-10-15.json.gz
- http://data.githubarchive.org/2012-03-10-16.json.gz
- http://data.githubarchive.org/2012-03-10-17.json.gz
- http://data.githubarchive.org/2012-03-10-18.json.gz
- http://data.githubarchive.org/2012-03-10-19.json.gz
- http://data.githubarchive.org/2012-03-10-20.json.gz
- http://data.githubarchive.org/2012-03-10-21.json.gz
- http://data.githubarchive.org/2012-03-10-9.json.gz
- http://data.githubarchive.org/2012-03-11-2.json.gz
- http://data.githubarchive.org/2013-03-05-20.json.gz
- http://data.githubarchive.org/2013-03-10-2.json.gz
- http://data.githubarchive.org/2013-05-31-22.json.gz
- http://data.githubarchive.org/2013-08-15-7.json.gz
- http://data.githubarchive.org/2013-09-06-0.json.gz
- http://data.githubarchive.org/2013-09-11-23.json.gz
- http://data.githubarchive.org/2013-09-28-9.json.gz
- http://data.githubarchive.org/2013-10-24-14.json.gz
- http://data.githubarchive.org/2013-11-25-15.json.gz
- http://data.githubarchive.org/2014-01-24-10.json.gz
- http://data.githubarchive.org/2014-03-09-2.json.gz
- http://data.githubarchive.org/2014-04-29-11.json.gz
- http://data.githubarchive.org/2014-04-29-12.json.gz
- http://data.githubarchive.org/2014-04-29-21.json.gz
- http://data.githubarchive.org/2014-07-17-12.json.gz
- http://data.githubarchive.org/2014-09-23-12.json.gz
- http://data.githubarchive.org/2014-09-30-14.json.gz
- http://data.githubarchive.org/2014-10-14-11.json.gz
- http://data.githubarchive.org/2014-10-19-16.json.gz
- http://data.githubarchive.org/2014-10-22-14.json.gz
- http://data.githubarchive.org/2014-10-28-17.json.gz
- http://data.githubarchive.org/2014-11-05-21.json.gz
- http://data.githubarchive.org/2016-01-28-1.json.gz

Idk if the GH API would allow us to fetch these now, but I figured I'd post this in case anyone else is wondering how complete the dataset is. Also, some of these might actually be from GH itself being down, but I haven't compared against https://status.github.com/ yet.

**Comment by igrigorik** [comment]
Some of those _are_ due to GitHub downtime, a few of them are due to issues with the crawler -- check closed issues for previous discussions around this. Unfortunately there is not much I can do here to "fix" either of the above. The files are missing.

Closing, but feel free to reopen if you feel that there is something actionable here.

**Comment by slang800** [comment]
Ah, I suppose we could add the list of known missing files to the website as documentation, but I don't think there's anything else actionable :(

**Comment by sainaen** [comment]
@igrigorik , @slang800 
At least for some missing/empty archives, there seems to be data in Google BigQuery daily datasets. For example, while [2014-01-24-10.json.gz](http://data.githubarchive.org/2014-01-24-10.json.gz) is empty, there are 12925 records in the BigQuery. Though, I should say, that I'm a BigQuery-newbie so maybe I'm missing something in my query:
```sql
SELECT count(*) as count
FROM [githubarchive:day.20140124]
WHERE hour(created_at) = 10
```

Assuming the events are really there, do you think it would be reasonable to try recover some archives this way?

**Comment by igrigorik** [comment]
This is odd. The BQ table are built **from** the archives, so going in the opposite direction doesn't make much sense to me. We need to dig deeper to understand what's going in here.

Group by hour on that day:

```
SELECT count(*) as count, hour(created_at) as hr
FROM [githubarchive:day.20140124]
GROUP by hr
ORDER BY hr asc
```

![image](https://cloud.githubusercontent.com/assets/10652/23414098/9fa0be22-fd8f-11e6-9a33-a619be6cf550.png)

There is a gap for 19 but 10 looks to be OK -- wonder if there is some timezone math we're not accounting for: https://cloud.google.com/bigquery/data-types#timestamp-type

**Comment by sainaen** [comment]
Oh. I think you're right, it's a timezones thing.

BigQuery dataset has timestamps in UTC, while json in the archive (at least for this day 2014-01-24) uses UTC-08:00, so I assume the filenames are also shifted. And so `2014-01-24 10:00 UTC-08` from the file is `2014-01-24 18:00 UTC` in the BigQuery, for which events are mostly missing (there are about ~900 records from that hour in the previous and the next archives.)

> There is a gap for 19…

It's actually a gap around 18:00, it's just a 19th row.

**Comment by igrigorik** [comment]
Right, that makes sense. Time math is hard. :)
