### ISSUE TITLE
2015 table not mentioned at https://www.githubarchive.org/

### ISSUE THREAD

**Issue by matkoniecz** [igrigorik/githubarchive.org#142]
https://www.githubarchive.org/

> year dataset: 2011, 2012, 2013, and 2014 tables contain all activities for each respective year

It suggests that project was abandoned in 2015. Assuming that it is active - I would expect 2015 and maybe also 2016 table to exist.

**Comment by slang800** [comment]
The graph at the top should make it pretty clear that it's still running, but that could be reworded with a PR to the gh-pages branch

**Comment by igrigorik** [comment]
![image](https://cloud.githubusercontent.com/assets/10652/15635545/bc67dc7a-2595-11e6-92b2-2fa486e4aad6.png)

Added the 2015 table and updated the landing page.
