### ISSUE TITLE
Could not get archives

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [igrigorik/githubarchive.org#143]
Hi there,

Kudos for your work here, first of all. <bows low>

I wanted to report, that trying to download archive files met with failure. I tried the following:
```

wget http://data.githubarchive.org/2015-05-\{01..29\}-\{0..23\}.json.gz
wget http://data.githubarchive.org/2015-01-\{01..30\}-\{0..23\}.json.gz
wget http://data.githubarchive.org/2016-05-28-\{0..23\}.json.gz
```

all met with `404 NOT FOUND`. In case files are removed, you may want to update the docs on the site, as they state you can get them with wget (or other HTTP client).

sincerely,
LAFK

**Comment by igrigorik** [comment]
I think you have an old version of Bash. Take a look at https://github.com/igrigorik/githubarchive.org/issues/6.

**Comment by LIttleAncientForestKami** [comment]
That was, indeed, the issue. My thanks and apology for bothering you with a trivial case.
