### ISSUE TITLE
What happened to repo and actor?

### ISSUE THREAD

**Issue by mikeal** [igrigorik/githubarchive.org#145]
I've been pulling down tarballs every month and all of a sudden the repo and actor objects are empty. What happened?

-Mikeal

**Comment by igrigorik** [comment]
Can you provide an example? 

```wget http://data.githubarchive.org/2016-06-24-12.json.gz```

```
{"id":"4191217793","type":"WatchEvent","actor":{"id":11061334,"login":"stefan-kern","display_login":"stefan-kern","gravatar_id":"","url":"https://api.github.com/users/stefan-kern","avatar_url":"https://avatars.githubusercontent.com/u/11061334?"},"repo":{"id":46077896,"name":"luruke/barba.js","url":"https://api.github.com/repos/luruke/barba.js"},"payload":{"action":"started"},"public":true,"created_at":"2016-06-24T12:00:00Z"}
```

**Comment by mikeal** [comment]
`get http://data.githubarchive.org/2015-01-01-15.json.gz`

`{"id":"2489651045","type":"CreateEvent","actor":{},"repo":{},"payload":{"ref":"master","ref_type":"branch","master_branch":"master","description`

Also, 

`wget http://data.githubarchive.org/2016-05-01-15.json.gz`

`{"id":"3958738849","type":"PushEvent","actor":{},"repo":{},"payload":{"push_id":1091982939,"size":1,"distinct_size":1,"ref":"refs/heads/master",`

**Comment by arfon** [comment]
@mikeal could you tell me if the same issue exists in the most recent files. e.g. `wget http://data.githubarchive.org/2016-06-24-15.json.gz`?

**Comment by arfon** [comment]
@igrigorik - it looks like a bug in writing out the scrubbed, unprocessed events. I've started a job to reprocess these (but they won't need importing as tables as it's just the `.tar.gz` files) which should be done by tomorrow sometime.

**Comment by igrigorik** [comment]
@arfon sgtm, thanks for tracking it down! I gave you write access to gs://data.githubarchive.org. Once the transform is done you can just `cp` and overwrite the existing files :)

**Comment by arfon** [comment]
> @arfon sgtm, thanks for tracking it down! I gave you write access to gs://data.githubarchive.org. Once the transform is done you can just cp and overwrite the existing files :)

Perfect, thanks. These are ready to upload now.

**Comment by marcocitus** [comment]
How long will the upload take? I'm preparing a talk which uses GitHub data and getting a little nervous ;)

**Comment by arfon** [comment]
@igrigorik - can you give me permissions on `gs://data.githubarchive.org` 🙏 😁 

@marcocitus - this should take a few hours once I've started the upload.

**Comment by igrigorik** [comment]
> @igrigorik - can you give me permissions on gs://data.githubarchive.org 🙏 😁

You should have write access already -- just verified. FWIW, I used your @github email address.

**Comment by arfon** [comment]
> You should have write access already -- just verified. FWIW, I used your @github email address.

Great. @marcocitus - I've just started the upload, it should be finished in the next couple of hours.

**Comment by marcocitus** [comment]
Great, thanks! 😊

**Comment by arfon** [comment]
> Great, thanks! 😊

@marcocitus - these should be uploaded now. Can you check these are looking better?

**Comment by igrigorik** [comment]
New data based on example in https://github.com/igrigorik/githubarchive.org/issues/145#issuecomment-228560368:

```
{"id":"3958738849","type":"PushEvent","actor":{"id":13402847,"login":"beanhun","gravatar_id":"","url":"https://api.github.com/users/beanhun","avatar_url":"https://avatars.githubusercontent.com/u/13402847?"},"repo":{"id":39330162,"name":"beanhun/etsydemo","url":"https://api.github.com/repos/beanhun/etsydemo"},"payload":{"push_id":1091982939,"size":1,"distinct_size":1,"ref":"refs/heads/master","head":"74e60d83ad5a7de75bedde66b5624b8ec93a5c35","before":"8c78eb6bef46e7ad063d4d440ac10335db5f0bfe","commits":[{"sha":"74e60d83ad5a7de75bedde66b5624b8ec93a5c35","author":{"email":"2b214d5a8d68162c3c02bd39bf7b443200dfb60c@gmail.com","name":"Bin Han"},"message":"Added Name to Users","distinct":true,"url":"https://api.github.com/repos/beanhun/etsydemo/commits/74e60d83ad5a7de75bedde66b5624b8ec93a5c35"}]},"public":true,"created_at":"2016-05-01T15:00:00Z"}
```

Both actor and repo data is there now, closing.
