### ISSUE TITLE
repo_name and repo_url formats vary before 2015

### ISSUE THREAD

**Issue by bburky** [igrigorik/githubarchive.org#147]
Sorry, for not checking this one at the same time as #146, but I just noticed this.

Compare `repo_name` and `repo_url` in months 201412 and 201501:
https://bigquery.cloud.google.com/table/githubarchive:month.201412
https://bigquery.cloud.google.com/table/githubarchive:month.201501

Before 2015, `repo_name` is of the format `{repo}`, and `repo_url` is of the format `https://github.com/{user}/{repo}`. As of 2015 `repo_name` is of the format `{user}/{repo}`, and `repo_url` is of the format `https://api.github.com/repos/{user}/{repo}`.

For now I can just parse the `repo_url` field, but you may want to make this consistent.

This is what works for now to parse `repo_url` for both before and after 2015:

```sql
select
    REGEXP_EXTRACT(repo_url, '/([^/]+)/[^/]+$') as user,
    REGEXP_EXTRACT(repo_url, '/[^/]+/([^/]+)$') as repo,
from [githubarchive:month.xxxxxx];
```

**Comment by igrigorik** [comment]
@bburky heads up / aside: the repo_url should be repo.url (a field within a record). This is mistake on my part, the tables are being rebuilt right now..

**Comment by bburky** [comment]
As in, you're currently changing the table schema right now in Big Query? Do I need to rerun my query? My query finished successfully, so I think it was fine.

**Comment by igrigorik** [comment]
FWIW, I'm inclined to close this as a wontfix. We can fix the keys of the schema but I don't think we can reasonably enforce a 100% consistent format across the values -- e.g. GitHub can decide to change its URL structure at any point, and I don't think that should mean that we now need to rewrite all of our events. Said differently, some level of user normalization will still be required.. which is exactly what you're doing. 

Yay/nay? Any strong objections? /cc @arfon

**Comment by bburky** [comment]
That's reasonable I suppose. But I'd almost say the `repo` column is useless. I think everything that's in `repo` is also in  `repo.url` but with a somewhat more consistent format.

**Comment by bburky** [comment]
If you're not going to normalize the data, perhaps it would be a good idea to start a wiki page on this repo so the community can document the inconstancies they find?

**Comment by arfon** [comment]
> FWIW, I'm inclined to close this as a wontfix. We can fix the keys of the schema but I don't think we can reasonably enforce a 100% consistent format across the values -- e.g. GitHub can decide to change its URL structure at any point, and I don't think that should mean that we now need to rewrite all of our events. Said differently, some level of user normalization will still be required.. which is exactly what you're doing.

👍 I think this is the right approach.

> If you're not going to normalize the data, perhaps it would be a good idea to start a wiki page on this repo so the community can document the inconstancies they find?

I also think this might be a smart thing to do. I would have *loved* to have this resource when writing [the event parser](https://github.com/arfon/gh_archive_parser) I was working on recently.

**Comment by igrigorik** [comment]
Good idea! Enabled wiki pages and created https://github.com/igrigorik/githubarchive.org/wiki/Archive-schema -- add your findings there!
