### ISSUE TITLE
Updated data format

### ISSUE THREAD

**Issue by ThisIsJohnBrown** [igrigorik/githubarchive.org#150]
Hello!

It seems like the public BigQuery data sets were moved in format. Are those historically formatted data sets available anywhere still?

We have an open source project that uses programatically generated SQL calls in BQ that are now not working.

Any info you can give me would be awesome!

Thanks!

@jlevinsohn31

**Comment by igrigorik** [comment]
No, unfortunately the old dataset is no longer available. However, the daily/monthly/yearly tables should contain all the same (and more) data.. you just need to update the queries. Please see: https://www.githubarchive.org/#bigquery
