### ISSUE TITLE
Reactions events

### ISSUE THREAD

**Issue by Dumbris** [igrigorik/githubarchive.org#151]
Is there any data about reactions +1, -1, etc (https://developer.github.com/v3/reactions/) available in githubarchive? I tried to scan a payload field in bigquery with regexp but without success.

**Comment by igrigorik** [comment]
Good question. Reactions appears to be in "developer preview" and I don't see them on the list of event types exposed through the API [1]. It *would* be great to have them there though! 

@arfon any idea if there are plans to expose these in the future?

[1] https://developer.github.com/v3/activity/events/types/

**Comment by arfon** [comment]
> @arfon any idea if there are plans to expose these in the future?

No idea sorry. I will ask!
