### ISSUE TITLE
List of md5/sha1 for each archive

### ISSUE THREAD

**Issue by maxwellmao** [igrigorik/githubarchive.org#153]
Hi folks,

Thanks for sharing such a wonderful dataset! I am conducting my research with the dataset.

I was wondering whether you have a list of md5 or sha1 for each archive that I can check the integrity of downloaded gzip files. I downloaded all archives via wget. However, I realized some of them are corrupted. It will be helpful for me to check which ones I need to re-download if you have a list of md5 or sha1.

**Comment by igrigorik** [comment]
Hmm, unfortunately I don't think so.. You can check the example format of each event here: https://developer.github.com/v3/activity/events/types/ -- quick search through that doesn't yield any md5's / sha's.

**Comment by jimmyye** [comment]
+1
I think @maxwellmao was asking for something like:
http://data.githubarchive.org/2015-01-01-15.json.gz.md5
to ensure 2015-01-01-15.json.gz is downloaded correctly.

**Comment by igrigorik** [comment]
Oh, I think I misinterpreted the request then.. No, we don't have MD5's, but I guess we could generate those. @maxwellmao can you point to some particular archives that we can double check?

**Comment by maxwellmao** [comment]
@jimmyye Thanks for reinterpreting!

@igrigorik I don't think you need double check any archive. The error happens because of some unexpected reasons when downloading. The list of md5 would help us to check the integrity of the downloaded archives. For example, I find the md5 of my downloaded archive 2015-01-01-15.json.gz is 291a178ae86e4034b9a4d0b1224ac349. However, the md5 of the archive you provide should be 304533a206bbe59809c438c69a94cf66. In that case, I need to re-download the archive 2015-01-01-15.json.gz from you.

I would suggest to have a file, maybe put it on http://data.githubarchive.org/md5, containing the md5 of all archives, like
```
4a2ea6029fe7f596ef394bcc8b2bd915  2011-02-12-0.json.gz
4c30324270def59dff0f48d6de1155c1  2011-02-12-1.json.gz
12a0aa09db5cd0988d8a15bc033a9fca  2011-02-12-2.json.gz
3ac8bc33beb4974cbf556b7e30edf7d0  2011-02-12-3.json.gz
8aa69475227f59d55b006341e86694fb  2011-02-12-4.json.gz
b25f584e6291498ea7fc1a19156865d4  2011-02-12-5.json.gz
3254332204a5f27c08463cf6976b924a  2011-02-12-6.json.gz
df10e4e150b4477945ed2db3fee675bf  2011-02-12-7.json.gz
d57ecb830a3389e61684f9a2ea4495fd  2011-02-12-8.json.gz
81d6db8855631fcaf3e16d1af42b4745  2011-02-12-9.json.gz
```

**Comment by igrigorik** [comment]
@maxwellmao I understand the intent, I'm just wondering if the particular files you ran into are corrupted on this end or during transfer.

Re, hashes. I recommend using gsutil to sync data, as it already performs these checks under the hood: https://cloud.google.com/storage/docs/gsutil/commands/hash

e.g. `gsutil cp gs://httparchive/2011-* .`

**Comment by maxwellmao** [comment]
I see. I re-downloaded the corrupted archives, and have not found any error yet. I will try gsutil in future.

**Comment by infinisil** [comment]
For future reference: The Google Cloud Storage API [can be used](https://cloud.google.com/storage/docs/json_api/v1/objects/list) to get MD5 hashes directly for e.g. a date range:

```
$ curl 'https://storage.googleapis.com/storage/v1/b/data.gharchive.org/o?startOffset=2023-01-01-0.json.gz&endOffset=2024-01-01-0.json.gz'
{
  "kind": "storage#objects",
  "nextPageToken": "ChUyMDIzLTAyLTExLTIyLmpzb24uZ3o=",
  "items": [
    {
      "name": "2023-01-01-0.json.gz",
      "md5Hash": "UrvzEvM8o09GfNcbRQ2h3Q==",
      [...]
    },
```

Make sure to set `&pageToken=<nextPageToken>` repeatedly to get all pages.
