### ISSUE TITLE
wget gives a 404 error

### ISSUE THREAD

**Issue by hketkar** [igrigorik/githubarchive.org#155]
Hi,
I am getting a 404 when I try to wget the gz files. 

The following works:
`wget http://data.githubarchive.org/2015-01-01-15.json.gz`

But this doesn't: 
`wget http://data.githubarchive.org/2015-01-01-{0..23}.json.gz`

and this doesn't:
`wget http://data.githubarchive.org/2015-01-{01..30}-{0..23}.json.gz`

Thanks!
Harsh

**Comment by igrigorik** [comment]
I bet you're seeing this due to old version of bash.. Take a look at https://github.com/igrigorik/githubarchive.org/issues/6.

**Comment by hketkar** [comment]
Thanks for your prompt response! Earlier I was using wget within Windows. The Wget commands worked fine on bash for Windows 10.
