### ISSUE TITLE
As seen on Google BigQuery, language doesn't seem to be populated

### ISSUE THREAD

**Issue by abeburnett** [igrigorik/githubarchive.org#156]
Running the following BigQuery query reveals that from January 1, 2015 until April 30, 2015 every single record had language = null. Is this a source data issue, or a BigQuery issue? 

```
SELECT year, language, name_count
FROM(
  SELECT LEFT(STRING(created_at), 4) as year, json_extract(payload, "$['forkee.language']") AS language, count(DISTINCT repo.name) AS name_count
  FROM (TABLE_DATE_RANGE([githubarchive:day.], 
      TIMESTAMP('2015-01-01'), 
      TIMESTAMP('2015-04-31')
    ))
    GROUP BY year, language
    )
ORDER BY year, name_count DESC
```

**Comment by igrigorik** [comment]
Source data issue.. unfortunately. Also, starting Jan 2016 we switched to the new events endpoint which, unfortunately, doesn't provide language data.
