### ISSUE TITLE
event types missing?

### ISSUE THREAD

**Issue by anarcat** [igrigorik/githubarchive.org#162]
I see there are [34 repository events in github](https://developer.github.com/v3/activity/events/types/#repositoryevent) yet the following query yields only 14 distinct events for 2016 in Google's big data thingie:

```
SELECT type FROM [githubarchive:year.2016] GROUP BY type ORDER BY type;
```

I have also tried this:

```
SELECT type FROM (
  TABLE_QUERY([githubarchive:month],
    'REGEXP_MATCH(table_id, r"^2016\d+")'
  ))
GROUP BY type
 ORDER BY type
```

Am I doing something wrong there or are some events missing? In particular, I am looking for RepositoryType events... I had high hopes I could see the number of repos created/destroyed in february and march, like this:

```
SELECT JSON_EXTRACT(payload, '$.action') as action FROM (
  TABLE_QUERY([githubarchive:month],
    'REGEXP_MATCH(table_id, r"^20170\d")'
  ))
WHERE type='RepositoryType'
GROUP BY action
```

now i ran out of quotas as well. ;)

**Comment by igrigorik** [comment]
From the docs.. "Events of this type are not visible in timelines. These events are only used to trigger hooks." As a result, afaik, they're not emitted to Events API and hence not logged by GH Archive. :(
