### ISSUE TITLE
Missing Data at 18:00 on 2016-10-21

### ISSUE THREAD

**Issue by WMBao** [igrigorik/githubarchive.org#164]
I am afraid there is something wrong with the GitHub archive data at 18:00 on 2016-10-21. 

The following command returns an error message saying 404 not found.

wget http://data.githubarchive.org/2016-10-21-18.json.gz

Could you check it please? Thanks.

**Comment by igrigorik** [comment]
GitHub was down for a couple of hours on that day: http://currentlydown.com/github.com#2016-10-21 -- hence no data. :(
