### ISSUE TITLE
Where are 2017-07-06-23.json.gz and later?

### ISSUE THREAD

**Issue by hut8** [igrigorik/githubarchive.org#165]
Hey @igrigorik ! What happened with 2017-07-06-23? Looks like that one didn't make it. Anything I can do to help?

**Comment by igrigorik** [comment]
Hmm, super odd.. Can't figure out why that file didn't make it. It was logged A-OK. Just did a manual push: http://data.githubarchive.org/2017-07-06-23.json.gz.

Let me know if you spot any other issues.
