### ISSUE TITLE
Missing pullrequestevents in githubarchive:year.2014

### ISSUE THREAD

**Issue by km-Poonacha** [igrigorik/githubarchive.org#166]
I have been using the githubarchive:year.2014 database for a project that analyses Push and PullRequestEvents of projects started in 2014. I have noticed some of the pullrequests available on github API is not included in the githubarchive database. 
For example, for the repo egret-labs/egret-core, the PR nos 18 [https://api.github.com/repos/egret-labs/egret-core/pulls/18], 12,11 .. can be found using the API but the same PR events are not found when searching for pullrequestevents in the githubarhive 2014 database.  
I have tried my sincere best to ensure that I have not missed anything. I have reached out since I have pretty much run out of ideas on why I am seeing this problem.

**Comment by igrigorik** [comment]
This is a tricky one to trace back and figure out with 100% certainty.. It could be due to a data gap or error in processing. Do you similar gaps for other projects in same date range? Also try expanding your search to other years -- as a sanity check.

**Comment by km-Poonacha** [comment]
Thank you Ilya for your response and I apologize for the delay. For the same data range (githubarchive:year.2014) I checked around 50 repos which are reasonably popular (more than 1000 stars) and that were started early in 2014. I found 8 of them were missing PRs. While most were missing one or two (Like repoid 18418026 is missing pr# 72, repoid 19961085 is missing pr# 1, 20101515 is missing pr# 513), two of the repos are missing a significant number of prs (repoid 16062915 missing pr#s 1- 7 and 9 and repoid 18077557 is missing many of its early PRs (around 270 of them )).
I will check the 2015 data archive in a similar fashion.

**Comment by km-Poonacha** [comment]
I finally checked the 2015 archive in a similar fashion (50 repos). I did not find any indication of missing events. It seems to me that this issue, however small, is restricted to the 2014 dataset.

**Comment by igrigorik** [comment]
@km-Poonacha thanks for digging in on this one. It's hard to say what exactly went wrong here, but it's possible that either (a) there were some issues with the GH API in 2014, (b) our crawler missed some events, or (c) the project... joined and was open-sourced later? Note that if you migrate a prpoject from another Git host / repository, then history is replicated as if it was always there, but the activity API wouldn't log all of it.

**Comment by km-Poonacha** [comment]
Thank you for these points and addressing my consern. I guess this should explain what i saw. In any case as long as it is some random PRs missing it is ok for my work. I was just worried if there was some systemic issue, and I am now confident it is not the case. Thanks.
