### ISSUE TITLE
GitHub archive JSON for 2017-11-08-1 contains error

### ISSUE THREAD

**Issue by lukaszgryglicki** [igrigorik/githubarchive.org#169]
See 2017-11-08-1 file.
Get it locally `wget http://data.githubarchive.org/2017-11-08-1.json.gz`
Ungzip `gzip -d 2017-11-08-1.json.gz`
Edit: `vim 2017-11-08-1.json`
Search for 6823705857: `/6823705857`
You will see broken, non closed string:
```
{"id":"6823685750","type":"DeleteEvent","actor":{"id":12358972,"login":"CodePipeline-Test","display_login":"CodePipeline-Test","gravatar_id":"","url":"https://api.{"id":"6823705857","type":"IssueCommentEvent","actor"
```

Starts with `"url":"https://api.{"id":"6823705857`
`url` starting from `"https://api.` is not closed and next event with id=6823705857 follows.

If I save this single line (single JSON) as `err.json` and then run jsonlint:
`jsonlint-php err.json`
I will see:
```
err.json: Parse error on line 1:
...url":"https://api.{"id":"6823705857","ty
----------------------^
Expected one of: 'EOF', '}', ':', ',', ']'
```
![screen shot 2017-11-15 at 15 12 50](https://user-images.githubusercontent.com/2469783/32840505-233291e8-ca18-11e7-9201-0480341de135.png)

**Comment by lukaszgryglicki** [comment]
ping

**Comment by lukaszgryglicki** [comment]
I had to add special code to guard against a single broken hour in all 4 years:
https://github.com/cncf/devstats/commit/9f89cebb13e5c408704c3bae116b1412d2c326fa#diff-02ad8f7df2887b21402be02a3539d60fR7

**Comment by igrigorik** [comment]
Sorry, missed this, thanks for the bump. Hard to say what happened there. At this stage the only thing we can do is manually fix the file and replace it.

**Comment by lukaszgryglicki** [comment]
Thanks.
I've added guardians for every project to skip that single hour, but I think it is worth fixing - many other projects depending on GHA could potentially fail on this hour.

**Comment by igrigorik** [comment]
@lukaszgryglicki yep. Updated the file, could you please verify before I close this?

**Comment by lukaszgryglicki** [comment]
Confirmed.
File imported OK.

**Comment by igrigorik** [comment]
Great. Thanks for reporting this!
