### ISSUE TITLE
Retrieving event archives for entire days or months not working

### ISSUE THREAD

**Issue by gvial666** [igrigorik/githubarchive.org#172]
Hi,

First of all, great project :)

I just wanted to know whether there was something specific that was required to retrieve gz archives for entire days or months. Using the wget examples provided on the readme, the following works:

wget http://data.githubarchive.org/2015-01-01-15.json.gz

However, the other two examples do not work and results in the following error (see screenshot attached). I can work around this using the BigQuery interface but I thought I'd mention it if it's a permission issue or something like that. For info, I get the same issue when I use the requests module in Python3 to do a GET.

![image](https://user-images.githubusercontent.com/33731143/34998223-7ce03f6e-faac-11e7-8068-ddcd424a2d8e.png)

**Comment by igrigorik** [comment]
We don't provide aggregated archive files. That example is meant to be used as shell expansion. That is, use wget or similar with modern bash, and it'll expand that sequence to fetch all the archives in the defined range.

**Comment by gvial666** [comment]
That makes a lot more sense... Thanks and sorry for the confusion!
