### ISSUE TITLE
One event only in some hours

### ISSUE THREAD

**Issue by bluecoco** [igrigorik/githubarchive.org#175]
Hello,

We are trying to using github data for building information flow simulation models and noticed that for the following hours in github archive, there is only one event recorded.
2015-01-06-4
2015-01-05-20
2015-01-07-13
2015-01-08-2
2015-01-09-11
2015-01-09-9
2015-02-03-16

Not sure if this can be fixed as these are 'ancient' data, but thought will give a heads-up.

Thank you for the great work and kindly sharing this valuable data.

**Comment by igrigorik** [comment]
Thanks for reporting this. Unfortunately nothing we can do about it at this point. :(

I'm sure you'll find a few other gaps as well.. Some of these may be due to maintenance on our side, but most of the time this is due API downtime @ GitHub.

**Comment by bluecoco** [comment]
Thank you for the prompt response. Just wanted to try my luck.:)
