### ISSUE TITLE
repository_closed_issues

### ISSUE THREAD

**Issue by aslakhellesoy** [igrigorik/githubarchive.org#29]
Hi there,

I'd like to use the BigTable query API to create charts showing the number of closed and open issues for a project over time.

An example of the chart I'd like to make is here: http://jira.codehaus.org/browse/JRUBY

githubarchive.org currently stores `repository_open_issues`, but in order to do this I'd also need `repository_closed_issues`.

Then I should be able to run a query like this:

```sql
SELECT created_at, repository_open_issues, repository_closed_issues
FROM [githubarchive:github.timeline]
WHERE repository_owner="rails"
    AND repository_name="rails"
    AND type="IssuesEvent"
    AND TIMESTAMP(created_at) > TIMESTAMP("2013-03-14 10:13:55")
ORDER BY created_at DESC
LIMIT 100
```

I poked around the source code to see if I could do this myself and send a pull request. I imagine I'd have to add the new field to `bigquery/schema.js`, but there must be something else that needs to be done as well to ensure github actually includes this field whenever an issue is created, closed or reopened. I'm not sure where this would be.

Any pointers would be greatly appreciated!

Cheers,
Aslak

**Comment by igrigorik** [comment]
Update: new `events_*` tables are using Events API and should contain all the necessary data.

**Comment by aslakhellesoy** [comment]
Fantastic!
