### ISSUE TITLE
Events appear twice

### ISSUE THREAD

**Issue by naorrosenberg** [igrigorik/githubarchive.org#36]
I ran the following query to list all WatchEvent of repository textmate/textmate by date:
```
SELECT actor_attributes_login, type, repository_name, repository_owner, created_at as date
FROM [githubarchive:github.timeline]
WHERE (type="WatchEvent")
    AND repository_name="textmate"
    AND repository_owner="textmate"
    AND payload_action="started"
ORDER BY date DESC
```

I think there are 2 possible issues with the results of this query:

1. The query returns 12,571 results, while in the repository page (https://github.com/textmate/textmate) there are only 1,215 watchers.
2. The results include many actor_attributes_login duplicates.

Your help is much appreciated in understanding this mismatch.

Thanks :)

**Comment by igrigorik** [comment]
This should be fixed in the new `events_*` tables in BigQuery.
