### ISSUE TITLE
unicode support

### ISSUE THREAD

**Issue by anvaka** [igrigorik/githubarchive.org#54]
Hello Ilya,

I was trying to get repository description via BigQuery UI, and noticed that some unicode symbols are not shown correctly. E.g. this query:

``` sql
SELECT repository_description FROM [githubarchive:github.timeline]
WHERE repository_name = 'baidupcsapi'
```

Returns:
```
Row	repository_description	 
1	������������api	 
2	������������api	 
3	������������api	 
4	������������api	 
5	������������api
```

While the actual description of [ly0/baidupcsapi](https://github.com/ly0/baidupcsapi) is `百度网盘api`

**Comment by igrigorik** [comment]
This should be fixed in the new `events_*` tables.
