### ISSUE TITLE
missing gzip compression for 2015

### ISSUE THREAD

**Issue by neelance** [igrigorik/githubarchive.org#79]
When I do
```
wget http://data.githubarchive.org/2015-01-01-15.json.gz
```
I get a plain JSON file that is not gzipped.

**Comment by igrigorik** [comment]
Hmm.. bah! Was hoping wget would automatically append the gzip header. 

`wget --header="accept-encoding: gzip" http://data.githubarchive.org/2015-01-01-15.json.gz`

Should probably add a note in the readme =/

**Comment by neelance** [comment]
This solution does not seem right to me. `Accept-Encoding: gzip` / `Content-Encoding: gzip` means that the transfer is gzip compressed, not the content after the transfer. Consider the following Go program:
```go
package main

import (
	"io"
	"net/http"
	"os"
)

func main() {
	resp, err := http.Get("http://data.githubarchive.org/2015-01-01-15.json.gz")
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()

	file, err := os.Create("2015-01-01-15.json.gz")
	if err != nil {
		panic(err)
	}
	defer file.Close()

	io.Copy(file, resp.Body)
}
```
Go automatically uses `Accept-Encoding: gzip`, but it also automatically decompresses the response if `Content-Encoding: gzip` is given in the response header. So if I want to store the gzipped version, I would need to compress it again or do some other hack. This code works fine for files before 2015.

**Comment by igrigorik** [comment]
You're right. Should be fixed now!

**Comment by neelance** [comment]
Thx!
