### ISSUE TITLE
BigQuery broken links

### ISSUE THREAD

**Issue by glebm** [igrigorik/githubarchive.org#84]
Hi Ilya,

Is the BigQuery dataset linked from the home page (https://bigquery.cloud.google.com/dataset/githubarchive) no longer available? 

Thanks

**Comment by igrigorik** [comment]
What makes you say that? It works just fine here. If you haven't already, make sure you follow the instructions to initialize a project first in the developer console first...

**Comment by fhoffa** [comment]
Try a link to an actual table instead: https://github.com/igrigorik/githubarchive.org/pull/85

**Comment by hut8** [comment]
Even though I use these tables a lot that link still doesn't work. In the developer console (the Chrome one), the page tries to load this, which is obviously JavaScript, and gets a 404 HTML page:
https://bigquery.cloud.google.com/js/bigquery.sourcemap
Then some JS assertions fail and it dies.

**Comment by igrigorik** [comment]
Closing, please feel free to reopen if this is still an issue.
