### ISSUE TITLE
JSON schema for event type 'PushEvent' does not match the schema posted in the README file 

### ISSUE THREAD

**Issue by harishvc** [igrigorik/githubarchive.org#86]
JSON schema for event type 'PushEvent' does not match the schema posted in the README file (https://github.com/igrigorik/githubarchive.org/blob/master/crawler/README.md) .  Some of the differences  include  ```repository``` is now ```repo``` , ```payload.sha``` and numerous ```repository``` attributes like ```language```, ```description``` are missing.  I first noticed this change 2 months ago. Any assistance will be much appreciated.

**Comment by igrigorik** [comment]
@harishvc good catch, thanks! Starting 01/01/2015 both the tables and the schema have changed.. For details see: www.githubarchive.org/#bigquery. I've updated the readme's to point to the new docs on the public site.

**Comment by harishvc** [comment]
@igrigorik Having additional meta-data in the schema (example: repository language, repository description, actor login) immensely adds value. Would it be possible to reconsider or provide alternate solution?

**Comment by igrigorik** [comment]
@harishvc that's more of a question to GitHub team and their Events API. The old API we were using is now deprecated, so that's not an option. Note that there is a lot of *additional* meta-data in the payload field.

**Comment by harishvc** [comment]
@igrigorik Thanks!  payload field is missing author.username. I have reached out to the GitHub team cc @briandoll .
