### ISSUE TITLE
Getting latest repository infos from Github Archive

### ISSUE THREAD

**Issue by vdaubry** [igrigorik/githubarchive.org#88]
Hi,

Thanks for this amazing work ! I tried to retrieve the latest infos about a repository using Google BigQuery on the github archive timeline dataset and got some weird results.

In order to get the latest event about a repo i tried to join on max(created_at) but i get vastly incomplete informations. Here is the query for the rails repo :

```
SELECT *
FROM [githubarchive:github.timeline] a
JOIN EACH
  (
     SELECT MAX(created_at) as max_created, repository_url
     FROM [githubarchive:github.timeline]
     GROUP EACH BY repository_url
  ) b
  ON 
  b.max_created = a.created_at and
  b.repository_url = a.repository_url
WHERE payload_ref_type="repository" AND a.repository_name = 'rails'
```

I know this dataset doesn't include data before 2011, but it should contain informations about recently active repositories

I don't understand the results of this query :

* This query only return events of type 'CreateEvent', which are always older than 'PushEvent'
* It doesn't return the main rails repository : https://github.com/rails/rails
* Github search reports 147,149 repositories with the name "rails", the query only return 476 repositories

Is my query false in some way, why don't it return PushEvents ?
Is there another trick about the github archive dataset ?

Thanks for your help,
Vincent

**Comment by igrigorik** [comment]
I'm not sure why you have the extra condition on created_at, but that aside.. The main difference here is that searching for "rails" on GitHub finds any repository that has "rails" in the name (and description, I believe), and not just repositories that match exact "rails" string. 

```
SELECT *
FROM [githubarchive:github.timeline] a
WHERE 
  payload_ref_type = "repository" 
  AND repository_name CONTAINS("rails")
```

Above query should get you closer.

**Comment by vdaubry** [comment]
Thanks for your answer, actually want only named exactly Rails, and i would like to have the most recent informations about them : number of stars ("repository_watchers" right ?) , number of forks, etc
That's why i was joining on MAX(created_at) , i thought it would only select the most recent event for each repo named Rails.

I think i understand the problem with my query now, when i run this query:

```
SELECT *
FROM [githubarchive:github.timeline] a
WHERE 
  payload_ref_type = "repository" 
  AND repository_name = "rails"
```
I get 1327 "CreatedEvent", it must be all event corresponding the creation of repository after 2011and that's probably why the main Rails repo doesn't appear ?

I think i should get the latest PushEvent about about each repository named Rails to get the informations i'm looking for.
Do you know how i could do that ?

I seems to get better by joining on MAX(repository_pushed_at) though there are a lot of duplicates repository_url in the results (different a_actor_attributes_login)

**Comment by igrigorik** [comment]
Be careful with repository_watchers, etc.. GitHub has changed the meaning of watchers, stargazers, etc, a few times over the years. Wish I had an exact answer, alas.. eyeball the data and see if that's what you're looking for.

> I get 1327 "CreatedEvent", it must be all event corresponding the creation of repository after 2011and that's probably why the main Rails repo doesn't appear?

Sounds plausible.

> I think i should get the latest PushEvent about about each repository named Rails to get the informations i'm looking for. Do you know how i could do that ?

Why not just filter by `type` and look for PushEvents + group by repository name, or some such?

**Comment by vdaubry** [comment]
I update this issue, i finally got the infos i needed with :
```
SELECT *
FROM [githubarchive:github.timeline] a
JOIN EACH
  (
     SELECT MAX(repository_pushed_at) as repository_pushed_at, repository_url
     FROM [githubarchive:github.timeline]
     where repository_name = 'rails'
     GROUP EACH BY repository_url
  ) b
  ON 
  b.repository_pushed_at = a.repository_pushed_at and
  b.repository_url = a.repository_url;
```
