### ISSUE TITLE
Test query on main page does not work

### ISSUE THREAD

**Issue by samtstern** [igrigorik/githubarchive.org#95]
The following query is listed on githubarchive.org

```
SELECT event as issue_status, COUNT(*) as cnt FROM (
  SELECT type, repo.name, actor.login,
    JSON_EXTRACT(payload, '$.action') as event, 
  FROM (TABLE_DATE_RANGE(day.events_, 
    TIMESTAMP('2015-01-01'), 
    TIMESTAMP('2015-02-01')
  )) 
  WHERE type = 'IssuesEvent'
)
GROUP by issue_status;
```

However if you create a new Google Developer's Console project and run that, you will get an error.  The solution is to replace `day.events_` with `githubarchive:day.events_`.

**Comment by igrigorik** [comment]
Thanks, should be fixed now!
