### ISSUE TITLE
Crawler might be losing events

### ISSUE THREAD

**Issue by FiloSottile** [igrigorik/githubarchive.org#96]
The new Events API does not support `per_page`, so the parameter crawler.rb uses is useless.

More importantly, it looks to me like the *Am I losing events?* uses `> 100`. Since the page limit is 30, that will never trigger and you wouldn't know if the crawler was getting behind.

I don't know Ruby, so I might be completely wrong. Feel free to close in case.

**Comment by igrigorik** [comment]
The API does support per_page and returns up to 100 records at a time. I've just checked the crawler logs and there have been a few momentary spikes over the past few weeks where we might have missed a few seconds of data. I've adjusted the logic a bit and will monitor it to see if that addresses it.

**Comment by FiloSottile** [comment]
Oh! The documentation is wrong. Great, I don't have to hammer the API.

> Events support pagination, however the per_page option is unsupported. The fixed page size is 30 items. Fetching up to ten pages is supported, for a total of 300 events.

Good to know, thanks :)
