### ISSUE TITLE
Access denied for year datasets in BigQuery

### ISSUE THREAD

**Issue by alexweissman** [igrigorik/githubarchive.org#97]
In Google BigQuery, I can access `day` and `month` datasets, but `year` datasets give me an access denied error:

![screen shot 2015-04-01 at 9 40 30 pm](https://cloud.githubusercontent.com/assets/5004534/6956224/bb8b6aae-d8b8-11e4-9711-538330d1f228.png)

**Comment by igrigorik** [comment]
Woops, must have flipped the wrong ACL bit somewhere. Thanks for the heads up, should be fixed now!

**Comment by alexweissman** [comment]
Awesome, thanks!
