### ISSUE TITLE
Getting total downloads for a release/repo

### ISSUE THREAD

**Issue by alexweissman** [igrigorik/githubarchive.org#98]
I'm trying to fetch the total number of downloads for each repo in a given [day,month,year].  From what I understand according to the [GitHub API](https://help.github.com/articles/getting-the-download-count-for-your-releases/), this is only accessible through the Releases API.

This is fine, but when I query the githubarchive.org dataset, I get a different result from when I directly ping GitHub's API.  This:
```
SELECT payload from [githubarchive:month.201501]
WHERE type = 'ReleaseEvent'
and repo_name = 'twbs/bootstrap'
```
gives me a `download_count` of `0`.  But when I go to the release API (https://api.github.com/repos/twbs/bootstrap/releases/864625), I get a `download_count` of ~800K.  I guess this has something to do with the record in githubarchive only being created when the ReleaseEvent happens, but not updated with new download counts.

So, is there another way I can get the current download count for a particular release?

**Comment by igrigorik** [comment]
AFAIK, this is as expected... GH emits a "release" event when a new release is pushed by the repo owner, and naturally the download count is 0 at that time. GH _does not_ fire "release" events for each download though, hence we don't get this data in GH Archive. You'd have to use the public API to get the download count data.

**Comment by alexweissman** [comment]
That makes sense, pretty much what I expected.  Thanks!
